### ISSUE TITLE
v1.6.1: databaseParser fails to detect library scopes (SR 0.4.2 & 0.4.4)

### ISSUE THREAD

**Issue by icebound777** [nanaian/vscode-star-rod#12]
> Failed to read database file [...]/battle_func_library.lib:
> Unknown scope: undefined

... as well the other 4 func_libraries

Probable cause:
/src/databaseParser.ts line 150 accesses non-existing array index for scope string `battle` formerly tokenized from `{scope=battle}` line in library file

see https://github.com/nanaian/vscode-star-rod/blob/d5ca63ee6e64db82e470f7759b7f83711fa1c9be/src/databaseParser.ts#L150

**Comment by bates64** [comment]
Ah, this is a result of a syntax change between 0.4.x and 0.5.x:
```diff
-{scope=battle}
+{scope=us:battle}
```

**Comment by bates64** [comment]
This bug introduced in [f134bef](https://github.com/nanaian/vscode-star-rod/commit/f134bef04c2852fc3e37768ff12d0e8e697d3dbb#diff-80d64c9dfafb5fcf61b6f3f75efabffc330771073bf16360946bc30b9e1be022)

**Comment by bates64** [comment]
A fix should be available in vscode-star-rod 1.6.2, let me know if it's still broken
