### ISSUE TITLE
Cannot open SR log if compile resulted in error message: Unable to read compile.log

### ISSUE THREAD

**Issue by icebound777** [nanaian/vscode-star-rod#14]
If StarRod encounters an error during mod compilation and I attempt to open the log file via the VSCode popup notification, the following error shows:

> Command 'Star Rod: Compile Mod' resulted in an error (cannot open file file://[path_to_mod_directory]/logs/compile.log.
> Detail: Unable to read file '[path_to_mod_directory]/logs/compile.log' (Error: Unable to resolve nonexistent file '[path_to_mod_directory]/logs/compile.log'))

This happens if the StarRod folder is not directly inside the mod's root folder, I'm assuming the Compile Mod command thinks that StarRod is in there instead of referencing the starRod.installDirectory setting.

see
https://github.com/nanaian/vscode-star-rod/blob/f323f6d36541b981521457b9d8d43c83a1d9ea17/src/Mod.ts#L88

**Comment by bates64** [comment]
This seems to be a change made in the latest versions of Star Rod; will fix asap.

Thanks for the in-depth issue!

**Comment by bates64** [comment]
Fixed by #15 I believe
