### ISSUE TITLE
ItemEntityScripts doesn't have highlighting

### ISSUE THREAD

**Issue by eldexterr** [nanaian/vscode-star-rod#4]
You can find the byte code here:
https://docs.google.com/document/d/16850z34UR9kO8RWVpmB6B3goL2qRdGGLlT3xY61l72s/edit#heading=h.b6b1w0udrag7

Although I dunno if we can actually do something like this in Star Rod:

```
#new:ItemScript $MyItemScript
{
SetVisible
SetTileSize ( .IconSize:32x32 )
Loop
	SetIcon     ( 60` ~ImageIcon:item/key/cake_done )
Restart
End
}
```
You should ask clover, if isn't the case just close this issue 👍

**Comment by bates64** [comment]
AFAIK these are just .mis files in Star Rod

**Comment by bates64** [comment]
Closing in favour of new issues
